/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CreateDepartment: typeof import('./src/components/CreateDepartment.vue')['default']
    CreateRole: typeof import('./src/components/CreateRole.vue')['default']
    CreateUser: typeof import('./src/components/CreateUser.vue')['default']
    Dashboard: typeof import('./src/components/Dashboard.vue')['default']
    DataTableUser: typeof import('./src/components/DataTableUser.vue')['default']
    EditField: typeof import('./src/components/editField.vue')['default']
    EditUser: typeof import('./src/components/EditUser.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    FooterBar: typeof import('./src/components/FooterBar.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
